### ISSUE TITLE
Finding Issue to test it locally,  "no such class with name 'Internship' found in the schema"

### ISSUE THREAD

**Issue by j-a-i-a-n-a-n-d** [desaianm/internship_finder#9]
`
File "C:\Users\USER\Desktop\stream-internship-finder\testenv\Lib\site-packages\grpc\_channel.py", line 1005, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "extract params: no such class with name 'Internship' found in the schema. Check your schema files for which classes are available"
        debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"extract params: no such class with name \'Internship\' found in the schema. Check your schema files for which classes are available", grpc_status:2, created_time:"2024-04-22T12:26:43.4968988+00:00"}"
`

I know this error is encountered because my Database is not populate with the Internship Schema, because I am using my own credentials and my DB is currently empty.
I need some guidance or direction on how to proceed to populate my db schema 'Internship'.

**Comment by desaianm** [comment]
Below is the code used to create collection and add to weaviate cluster from url: import weaviate
import requests
import os
import weaviate.classes as wvc
from weaviate.classes.config import Property, DataType
import json

# json file for batch import
with open('final_internships.json') as f:
    data = json.load(f)



# Environment variables and URLs
url = "https://internship-finder-52en6hka.weaviate.network"
apikey = os.getenv("WCS_API_KEY")
openai_api_key = os.getenv("OPENAI_API_KEY")

# Connect to Weaviate
client = weaviate.connect_to_wcs(
    cluster_url=url,  
    auth_credentials=weaviate.auth.AuthApiKey(apikey
    ),
    headers={
        "X-OpenAI-Api-Key": openai_api_key  
    }  
)

client.collections.delete("Internship")
class_object = {
            "class": "Internship",
            "vectorizer": "text2vec-openai",
            "moduleConfig": {
                                "text2vec-openai": {  # this must match the vectorizer used
                                    "model": "text-embedding-3-large",
                                    "dimensions": 3072,  # Parameter only applicable for `v3` model family and newer
                                    "type": "text",
                                    "vectorizeClassName": False       
                            }
                    },
            "properties": [
                {
                    "name": "name",
                    "dataType": ["text"],
                },
                {
                    "name": "company",
                    "dataType": ["text"],
                    
                },
                {
                    "name": "date_published",
                    "dataType": ["text"],
                    
                },
                {
                    "name": "location",
                    "dataType": ["object"],
                   
                    "nestedProperties": 
                    [
                        {"dataType": ["text"], "name": "country"},
                        {"dataType": ["text"], "name": "city"},
                        {"dataType": ["text"], "name": "state"}
                    ],
                },
                {
                    "name": "roles",
                    "dataType": ["text[]"],
                    "moduleConfig": {
                                "text2vec-openai": {  # this must match the vectorizer used
                                    "skip": True
                                }
                    }
                },
                {
                    "name": "skills",
                    "dataType": ["text[]"],
                    "moduleConfig": {
                                "text2vec-openai": {  # this must match the vectorizer used
                                   "skip":True 
                                }
                    }
                },
                {
                    "name": "Eligibility",
                    "dataType": ["object"],
                    "moduleConfig": {
                                "text2vec-openai": {  # this must match the vectorizer used
                                    "skip": True,
                                    "vectorizePropertyName": True
                                }
                    },
                    "nestedProperties": 
                    [
                        {"dataType": ["text"], "name": "degree"},
                        {"dataType": ["text[]"], "name": "field"},
                        {"dataType": ["text[]"], "name": "experience"}
                    ],
                },
                {
                    "name": "summary",
                    "dataType": ["text"],
                    "moduleConfig": {
                                "text2vec-openai": {  # this must match the vectorizer used
                                    "skip": False,
                                    "vectorizePropertyName": False      
                                    }
                    }
                }
            ]
      
} 
  


client.collections.create_from_dict(class_object)




# Data to generate embeddings for and store in Weaviate
jeopardy = client.collections.get("Internship")

with jeopardy.batch.dynamic() as batch:
    for item in data:
        batch.add_object(properties=item)


collection = client.collections.get("Internship")

for item in collection.iterator():
    print(item.properties)

client.close()
